### ISSUE TITLE
Automatic updating of ModuleTable.csv

### ISSUE THREAD

**Issue by ianmcampbell** [ianmcampbell/Arcus-Modular-Education-Support-System#11]
Write an app.R that updates the ModuleTable.csv file and commits the change to GitHub

**Comment by braunsb** [comment]
I don't suppose the same app could update it on the server as well?

**Comment by ianmcampbell** [comment]
www.a-mess.org/TableUpdater/ now allows for addition of lines to ModuleTable.csv which are pushed to GitHub
