### ISSUE TITLE
New package

### ISSUE THREAD

**Issue by braunsb** [ianmcampbell/Arcus-Modular-Education-Support-System#4]
I don't know if you already have this one in the list:

`readr`

It needs to be on the server to run the paired t test lesson and many others that are not yet written. Thanks!

**Comment by braunsb** [comment]
Another new package I'm pretty sure isn't on the server:
`coin`

**Comment by braunsb** [comment]
I loaded `coin` on the server. Does it need to go in the script as well?

**Comment by ianmcampbell** [comment]
Added to start up script and installed on server for immediate use.
