### ISSUE TITLE
New lesson doesn't appear in the LESSONS LIST

### ISSUE THREAD

**Issue by braunsb** [ianmcampbell/Arcus-Modular-Education-Support-System#6]
I added a new lesson following the instructions on the wiki page for adding a new lesson. After adding the lesson and updating the module table.csv file, I saw no change in the list of lessons on the server. The last lesson should now be "paired t test" but it is kruskal-wallis test.

**Comment by ianmcampbell** [comment]
This issue is due to caching. For app.R, you can invalidate the cache by issuing `touch app.R` command. For .Rmd documents, you must restart the server.  See https://github.com/rstudio/rmarkdown/issues/1278

**Comment by braunsb** [comment]
Perhaps I didn't ask my question clearly: the LIST OF LESSONS on the server is what did not get updated. I think that's because the module table, the csv file, didn't get updated. It probably is a caching issue, as you say, but I don't know how to fix it. Is it like the app.R file, for which a `touch` is sufficient, or is it like the .Rmd file, for which a server restart is necessary? Thanks!
