### ISSUE TITLE
Links to our lessons not working from within learnr

### ISSUE THREAD

**Issue by braunsb** [ianmcampbell/Arcus-Modular-Education-Support-System#7]
Here is the text from the lesson: 

 [One-Sample _t_ Test]("http://www.a-mess.org/sb-one-sample-t-test/) and [Two-Sample _t_ Test]("http://a-mess.org/sb-two-sample-t-test/").

Here is the link that gets called:

http://www.a-mess.org/sb-paired-t-test/%22http://a-mess.org/sb-two-sample-t-test/%22

**Comment by ianmcampbell** [comment]
Duplicate of #5
