### ISSUE TITLE
Question: How long does it take to restart the server?

### ISSUE THREAD

**Issue by braunsb** [ianmcampbell/Arcus-Modular-Education-Support-System#8]
I fixed a typo in the paired t test lesson, then after pushing the change to the GitHub repo "Lessons", I restarted the server to capture this plus some other fixes. The typo is still there. Note that in the screenshot there are not closing quotation marks at the end of “The mean difference between paired observations is zero.

<img width="938" alt="Screen Shot 2019-11-11 at 8 59 08 AM" src="https://user-images.githubusercontent.com/45043455/68592735-c1eb8d00-0461-11ea-9e24-5238fe4aa0fa.png">

However, in the latest version of that file, the quotation marks are there.  How long after a server restart does it take for a change to appear? Thanks!

**Comment by ianmcampbell** [comment]
Documented [in the Wiki](https://github.com/ianmcampbell/Arcus-Modular-Education-Support-System/wiki/Updating-Lessons)

**Comment by braunsb** [comment]
Okay, I did all that, and am not seeing updates after the server restarts. That's why I'd like to know how long I should wait before deciding the update didn't "take."

**Comment by braunsb** [comment]
Before you close this, I wonder if you could answer the bit about how long is too long to wait for a lesson to change once the server has been restarted.

**Comment by ianmcampbell** [comment]
![image](https://user-images.githubusercontent.com/12883769/68607840-91b2e700-047f-11ea-9b93-0885a767d7ce.png)
I just looked at the file on the server. The closing quote is still missing. Thus, it's not a caching issue, but rather not updating the file on the server. 

Updates occur during a server restart.
